### ISSUE TITLE
Win10 작동실패

### ISSUE THREAD

**Issue by 39572910** [Regentag/SecureDNS#1]
재부팅해서 www.duckduckgo.com 연결 시도해봤지만 실패
![InstFail](https://user-images.githubusercontent.com/49832207/56468281-2b279680-6465-11e9-8994-f432e5c9d58e.PNG)

**Comment by Regentag** [comment]
관리자 권한으로 실행해도 동일한 증상이신거죠?
Windows 10 장비가 없어서 테스트를 못 해보고 있네요.

**Comment by 39572910** [comment]
이런 이슈를 실수로 닫아 버렸다..
네 관리자 권한으로 실행했습니다.

**Comment by Regentag** [comment]
설치파일을 사용하여 설치하도록 개선하였습니다.
https://github.com/Regentag/SecureDNS/releases/tag/release-1.1

재부팅 후 접속이 되지 않으셨던 문제는 아마도 'A socket operation was attempted to an unreachable host.' 오류가 발생하였을 가능성이 있습니다.
윈도에서 어댑터를 초기화 하기 전에 사용을 시도하여 발생하는 것으로 보이며, 수정된 코드가 1.1버전 설치파일에 반영되었습니다.
